### ISSUE TITLE
Create a backend server

### ISSUE THREAD

**Issue by jdmedlock** [jdmedlock/chs73#14]
**__Feature Description__**
Create a backend server

**__Major User Stories/tasks__**
- [x] Identify hosting service
- [x] Create webserver
- [x] Define GraphQL skeleton & API
- [x] Add MailJet integration & email distribution mutation
**__Additional Considerations__**
TBD
